### PR TITLE
Replace glimmer icon

### PR DESCRIPTION
**Pull request by kaermorchen**
The icon is too heavy right now. I have reversed the color and removed the circle.

It will look something like that:

### CODE REVIEW

**Comment by lifeart** [comment]
Hi @kaermorchen! Thank for observation! I agree with concerns. Could we somehow adjust centering?
At the moment it looks unbalanced and left-floated -

**Comment by lifeart** [comment]
In addition we could have `.gts` icon in blue color (to match ts) https://github.com/lifeart/glimmerx-workshop/blob/master/favicon.svg

**Comment by kaermorchen** [comment]
TS icon is added.

**Comment by kaermorchen** [comment]
> At the moment it looks unbalanced and left-floated -

I have no idea why it unbalanced. The icons have the same size (32px) like another icons from [seti-ui theme](https://github.com/jesseweed/seti-ui/tree/master/icons).

**Comment by kaermorchen** [comment]
Oh, Seti UI uses font icons, not svg

**Comment by lifeart** [comment]
@kaermorchen I able to center it using `viewBox="-3 0 32 32"`

**Comment by kaermorchen** [comment]
> @kaermorchen I able to center it using `viewBox="-3 0 32 32"` (changes pushed)

Will it be centered in another icon theme, like [vscode-icons](https://github.com/vscode-icons/vscode-icons)?

**Comment by lifeart** [comment]
it seems nope: 
image

**Comment by kaermorchen** [comment]
🤦 fucking icons...

**Comment by kaermorchen** [comment]
Lets it be as it is

**Comment by lifeart** [comment]
@kaermorchen how about this case? 
image

**Comment by evoactivity** [comment]
My desginer brain needs to fix those icons properly. Shouldn't need to use negative values in the viewbox, the icon is right aligned, it just needs nudging to the left. I can create proper cut outs for the JS/TS tags too.

**Comment by kaermorchen** [comment]
Another variants

icons

**Comment by kaermorchen** [comment]
mustache-ts
mustache-js
g-ts
g-js

**Pull request merged**
