### PR TITLE
CI: Commit package.json after version bump

### PR DESCRIPTION
**Pull request by evoactivity**
This should keep the package.json version in sync with gitversion

### CODE REVIEW

**Review by lifeart — APPROVED** [review]

**Comment by lifeart** [comment]
@evoactivity thank you!

**Comment by lifeart** [comment]
@evoactivity do we have formatting options for package json? 
At the moment it's inlined:

```json
{"name":"vscode-glimmer-syntax","displayName":"Glimmer Templates Syntax for VS Code","description":"Glimmer templates syntax","version":"1.0.11","author":"Aleksandr Kanunnikov <lifeart92@gmail.com>","license":"MIT","publisher":"lifeart","icon":"icon.png","preview":true,"repository":{"type":"git","url":"https://github.com/lifeart/vsc-ember-syntax"},"bugs":{"url":"https://github.com/lifeart/vsc-ember-syntax/issues"},"homepage":"https://github.com/lifeart/vsc-ember-syntax","engines":{"vscode":"^1.31.0"},"categories":["Programming Languages","Themes"],"keywords":["Ember.js","Glimmer","Handlebars","Syntax"],"activationEvents":["onLanguage:javascript","onLanguage:typescript"],"main":"./out/index.js","browser":"./out/worker.js","scripts":{"vscode:prepublish":"yarn node:package && yarn web:package","compile":"tsc -p ./","watch":"tsc -w -p ./","vs:package":"vsce package --yarn","vs:publish":"vsce publish --yarn","vs:publish:ci":"vsce publish --yarn --pat $VSCODE_STORE_TOKEN","ov:publish:ci":"ovsx publish --yarn --pat $OPEN_VSX_STORE_TOKEN","node:package":"webpack --mode production","web:package":"webpack --mode production","chrome":"vscode-test-web --browserType=chromium --extensionDevelopmentPath=."},"extensionKind":["ui"],"contributes":{"languages":[{"id":"glimmer-js","aliases":["Glimmer JS","gjs"],"extensions":[".gjs"],"configuration":"./languages/inline-template.configuration.json","icon":{"light":"./assets/glimmer-js.svg","dark":"./assets/glimmer-js.svg"}},{"id":"glimmer-ts","aliases":["Glimmer TS","gts"],"extensions":[".gts"],"configuration":"./languages/inline-template.configuration.json","icon":{"light":"./assets/glimmer-ts.svg","dark":"./assets/glimmer-ts.svg"}},{"id":"handlebars","extensions":[".hbs"],"aliases":["handlebars","hbs"],"configuration":"./languages/handlebars.configuration.json"}],"grammars":[{"language":"glimmer-js","path":"./syntaxes/glimmer-js.json","scopeName":"source.gjs","embeddedLanguages":{"source.gjs":"javascript"},"unbalancedBracketScopes":["keyword.operator.relational","storage.type.function.arrow","keyword.operator.bitwise.shift","meta.brace.angle","punctuation.definition.tag","keyword.operator.assignment.compound.bitwise.ts"]},{"language":"glimmer-ts","path":"./syntaxes/glimmer-ts.json","scopeName":"source.gts","embeddedLanguages":{"source.gts":"typescript"},"unbalancedBracketScopes":["keyword.operator.relational","storage.type.function.arrow","keyword.operator.bitwise.shift","meta.brace.angle","punctuation.definition.tag","keyword.operator.assignment.compound.bitwise.ts"]},{"label":"Handlebars (Ember)","language":"handlebars","scopeName":"text.html.handlebars","path":"./syntaxes/handlebars.tmLanguage.json"},{"injectTo":["source.js","source.ts"],"scopeName":"inline.hbs","path":"./syntaxes/inline-hbs.json","embeddedLanguages":{"meta.embedded.block.html":"handlebars"}},{"injectTo":["source.gts","source.gjs"],"scopeName":"inline.template","path":"./syntaxes/inline-template.json","embeddedLanguages":{"meta.embedded.block.html":"handlebars","meta.js.embeddedTemplateWithoutArgs":"handlebars","meta.js.embeddedTemplateWithArgs":"handlebars"}}],"typescriptServerPlugins":[{"name":"typescript-hbs-plugin","enableForWorkspaceTypeScriptVersions":true}],"jsonValidation":[{"fileMatch":"jsconfig*.json","url":"./schemas/tsconfig.schema.json"},{"fileMatch":"tsconfig*.json","url":"./schemas/tsconfig.schema.json"}]},"volta":{"node":"12.20.1","yarn":"1.22.10"},"dependencies":{"typescript-hbs-plugin":"^0.1.1"},"devDependencies":{"@types/node":"^12.7.5","@types/vscode":"^1.31.0","@vscode/test-web":"^0.0.15","ovsx":"^0.2.1","path-browserify":"^1.0.1","ts-loader":"^9.2.3","typescript":"^4.1.3","vsce":"1.100.1","webpack":"^5.44.0","webpack-cli":"^4.7.2"}}
```

**Comment by evoactivity** [comment]
That's unexpected.  I assume that's down to this actions https://github.com/onlyutkarsh/patch-files-action/.

We could add prettier and run a step after the version is updated to fix the file? That sound ok?

**Comment by evoactivity** [comment]
#39 added prettier formatting step here, also ran it on the repo so everything is now "correct".

**Pull request merged**
