### PR TITLE
fix precompileTemplate highlighting

### LINKED ISSUE #35: Proper precomile template support
image

### PR DESCRIPTION
**Pull request by evoactivity**
fixes #35

image

### CODE REVIEW

**Comment by lifeart** [comment]
@evoactivity still getting issue:


```ts
import Component from '@glimmer/component';
import { precompileTemplate } from '@ember/template-compilation';
import Local from './local';
import TemplateOnlyComponent from '@/components/OnlyTemplate/component.hbs';

const calculateSummary = (a: number, b: number) => `${a}+${b}=${a + b}`;
export default class HelloWorld extends Component {

  static template = precompileTemplate(
    `
    `,
    {
      isStrictMode: true,
      scope: () => ({
        Local,
        calculateSummary,
        TemplateOnlyComponent,
      }),
    }
  );
}
```

image

**Comment by evoactivity** [comment]
Looking ok for me

image

**Comment by evoactivity** [comment]
So I can get it to be this

image

but if I put a new line after the comma it breaks and I don't know why

image

**Comment by evoactivity** [comment]
I got a fix :)

image

**Comment by evoactivity** [comment]
This isn't a blocker but just maing a note.

The only thing that seems to be missing is prettier running on the embedded handlebars, I'm not sure what is missing to make that work or if that is something handled outside of the grammar.

It is a registered as handlebars, but not sure if that is what triggers it. 
image

**Comment by lifeart** [comment]
@evoactivity may be from here: https://github.com/search?q=repo%3Alifeart%2Fvsc-ember-syntax%20handlebars&type=code

**Comment by evoactivity** [comment]
I also don't get prettier running for ``` hbs`<div></div>` ``` blocks, which I haven't touched. Ultimately prettier just sees them as strings. I guess we'd need a prettier plugin to mark those strings as embedded languages.

**Comment by lifeart** [comment]
@evoactivity try to comment this line: https://github.com/lifeart/vsc-ember-syntax/blob/master/package.json#L36 (where we importing support scripts, to avoid side-effects caused by typescript-hbs-plugin)

**Comment by evoactivity** [comment]
Doesn't seem to make a difference.

**Review by lifeart — APPROVED** [review]

**Pull request merged**
